spring.application.name=Exam-Portal

spring.datasource.url=jdbc:postgresql://localhost:5000/onlineExamPortal?TimeZone=Asia/Kolkata
spring.datasource.username=sid
spring.datasource.password=2371
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata

jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
jwt.expiration=86400000